prerequisite_graph = {
    "PCC" : "Pasadena City College",
    "Pasadena City College": {
        # Computer Science Department
        "CS 001": {
            "name": "Introduction to Computers and Programming",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["CS 003B", "CS 003C"],
            "department": "computer science",
        },
        "CS 002": {
            "name": "Fundamentals of Computer Science I",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 008",), ("MATH 009",)],  # OR relationship
            "unlocks": ["CS 003A", "CS 006", "CS 066", "CS 018", "CS 045", "CS 034", "MATH 022"],
            "department": "computer science",
        },
        "CS 003A": {
            "name": "Fundamentals of Computer Science II (C++)",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 002",)],
            "unlocks": ["CS 008", "CS 018"],
            "department": "computer science",
        },
        "CS 003B": {
            "name": "Fundamentals of Computer Science (Java)",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 001",)],
            "unlocks": ["CS 033", "CS 018", "CS 045"],
            "department": "computer science",
        },
        "CS 003C": {
            "name": "Fundamentals of Computer Science (Python)",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 001",)],
            "unlocks": ["CS 018", "CS 045", "CS 034"],
            "department": "computer science",
        },
        "CS 006": {
            "name": "Introduction to Applied Logic Design",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 002",)],
            "unlocks": [],
            "department": "computer science",
        },
        "CS 008": {
            "name": "Fundamentals of Computer Science III – Data Structures",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 003A",)],
            "unlocks": ["CS 038"],
            "department": "computer science",
        },
        "CS 018": {
            "name": "Unix Scripting with Bash",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 002",), ("CS 003A",), ("CS 003B",), ("CS 003C",)],  # OR relationship
            "unlocks": [],
            "department": "computer science",
        },
        "CS 031": {
            "name": "Introduction to Data Science",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["CS 034"],
            "department": "computer science",
        },
        "CS 033": {
            "name": "Advanced Java Programming and Algorithm with Data Structures",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("CS 003B",)],
            "unlocks": [],
            "department": "computer science",
        },
        "CS 034": {
            "name": "Advanced Python Programming and Basic Data Structures",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("CS 031",), ("CS 003C",), ("CS 002",), ("CIS 012",)],  # OR relationship
            "unlocks": [],
            "department": "computer science",
        },
        "CS 038": {
            "name": "Introduction to Software Engineering",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("CS 008",)],
            "unlocks": [],
            "department": "computer science",
        },
        "CS 045": {
            "name": "Discrete Structures with Computer Science Applications",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("CS 002",), ("CS 003A",), ("CS 003B",), ("CS 003C",)],  # OR relationship
            "unlocks": [],
            "department": "computer science",
        },
        "CS 066": {
            "name": "Assembly Language Programming for the Sciences and Mathematics",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("CS 002",)],
            "unlocks": [],
            "department": "computer science",
        },
        "CS 137": {
            "name": "R Programming for Data Science",
            "units": 2.0,
            "difficulty": 2,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": [],
            "department": "computer science",
        },

        # Mathematics Department
        "MATH 003": {
            "name": "College Algebra for STEM",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["MATH 008", "MATH 006A"],
            "department": "mathematics",
        },
        "MATH 005A": {
            "name": "Single Variable Calculus I",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": True,  # Based on "placement based on the Math assessment process"
            "prerequisites": [("MATH 008", "MATH 009")],  # AND relationship
            "unlocks": ["MATH 005B", "MATH 022", "MATH 065", "ENGR 018"],
            "department": "mathematics",
        },
        "MATH 005B": {
            "name": "Single Variable Calculus II",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("MATH 005A",)],
            "unlocks": ["MATH 005C", "MATH 010", "MATH 055", "ENGR 011", "ENGR 015B"],
            "department": "mathematics",
        },
        "MATH 005C": {
            "name": "Multivariable Calculus",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B",)],
            "unlocks": [],
            "department": "mathematics",
        },
        "MATH 006A": {
            "name": "Calculus for Life Sciences I",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 003", "MATH 009")],  # AND relationship
            "unlocks": [],
            "department": "mathematics",
        },
        "MATH 008": {
            "name": "Precalculus Trigonometry",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 003",)],
            "unlocks": ["MATH 005A", "ENGR 001A", "ENGR 002"],
            "department": "mathematics",
        },
        "MATH 009": {
            "name": "Precalculus Mathematics",
            "units": 6.0,
            "difficulty": 5,  # Note: listed as 6/5 in data, capping at 5
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["MATH 005A", "MATH 006A", "ENGR 001A", "ENGR 002"],
            "department": "mathematics",
        },
        "MATH 010": {
            "name": "Linear Algebra and Applications",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B",)],
            "unlocks": [],
            "department": "mathematics",
        },
        "MATH 022": {
            "name": "Discrete Mathematics",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 005A", "CS 002")],  # AND relationship
            "unlocks": [],
            "department": "mathematics",
        },
        "MATH 055": {
            "name": "Differential Equations",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B",)],
            "unlocks": ["ENGR 016"],
            "department": "mathematics",
        },
        "MATH 065": {
            "name": "Scientific and Mathematical Programming",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 005A",)],
            "unlocks": [],
            "department": "mathematics",
        },

        # English Department
        "ENGL 001A": {
            "name": "Reading and Composition",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["ENGL 001B", "ENGL 001C", "ENGL 005A", "ENGL 006", "ENGL 007", "ENGL 008", "ENGL 009", "ENGL 020"],
            "department": "english",
        },
        "ENGL 001B": {
            "name": "Reading and Composition",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("ENGL 001A",)],
            "unlocks": ["ENGL 026"],
            "department": "english",
        },
        "ENGL 001C": {
            "name": "Intermediate Composition-Critical Thinking and Argument",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("ENGL 001A",)],
            "unlocks": [],
            "department": "english",
        },

        # Physics Department
        "PHYS 002A": {
            "name": "General Physics I: Mechanics and Thermal Physics",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("MATH 009",)],
            "unlocks": ["PHYS 002B", "PHYS 020"],  # Added PHYS 020
            "department": "physics",
        },
        "PHYS 002B": {
            "name": "General Physics II: Electromagnetism, Optics, and Modern Physics",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": False,
            "prerequisites": [("PHYS 002A",)],
            "unlocks": ["PHYS 020"],  # Added PHYS 020
            "department": "physics",
        },
        "PHYS 008A": {
            "name": "Physics for Scientists and Engineers I: Mechanics",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B",)],
            "unlocks": ["PHYS 008B", "PHYS 020", "ENGR 011", "ENGR 014"],  # Added cross-department unlocks
            "department": "physics",
        },
        "PHYS 008B": {
            "name": "Physics for Scientists and Engineers II: Waves, Electricity & Magnetism",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("PHYS 008A", "MATH 005C")],
            "unlocks": ["PHYS 008C", "PHYS 020", "ENGR 016"],  # Added ENGR 016
            "department": "physics",
        },
        "PHYS 008C": {
            "name": "Physics for Scientists and Engineers III: Thermodynamics, Optics, and Modern Physics",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("PHYS 008B", "MATH 005C", "MATH 055")],
            "unlocks": ["PHYS 020"],  # Added PHYS 020
            "department": "physics",
        },
        "PHYS 010": {
            "name": "Descriptive Introduction to Physics",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 009",)],
            "unlocks": ["PHYS 010L", "PHYS 020"],  # Added PHYS 020
            "department": "physics",
        },
        "PHYS 031A": {
            "name": "Calculus-Based College Physics I",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("MATH 005A",)],
            "unlocks": ["PHYS 031B", "PHYS 020"],  # Added PHYS 020
            "department": "physics",
        },
        "PHYS 010L": {
            "name": "Descriptive Physics in the Laboratory",
            "units": 1.0,
            "difficulty": 2,
            "assessment_allow": False,
            "prerequisites": [("PHYS 010",)],
            "unlocks": [],
            "department": "physics",
        },
        "PHYS 020": {
            "name": "Independent Study",
            "units": 2.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [
                ("PHYS 002A",), ("PHYS 002B",), ("PHYS 008A",),
                ("PHYS 008B",), ("PHYS 008C",), ("PHYS 010",),
                ("PHYS 031A",), ("PHYS 031B",)
            ],
            "unlocks": [],
            "department": "physics",
        },
        "PHYS 031B": {
            "name": "Calculus-Based College Physics II",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [("PHYS 031A", "MATH 005B")],
            "unlocks": [],
            "department": "physics",
        },
        "PHYS 108": {
            "name": "Introductory Physics for Scientists and Engineers",
            "units": 2.0,
            "difficulty": 2,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": [],
            "department": "physics",
        },

        # Chemistry Department
        "CHEM 001A": {
            "name": "General Chemistry and Chemical Analysis I",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": True,  # Based on assessment process mentioned
            "prerequisites": [("CHEM 022",)],
            "unlocks": ["ENGR 014"],
            "department": "chemistry",
        },
        "CHEM 022": {
            "name": "Introductory Chemistry",
            "units": 5.0,
            "difficulty": 5,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["CHEM 001A"],
            "department": "chemistry",
        },

        # Engineering Department
        "ENGR 001A": {
            "name": "Surveying",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 008", "MATH 009")],  # AND relationship
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 002": {
            "name": "Engineering Graphics",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 008", "MATH 009")],  # AND relationship
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 010": {
            "name": "Introduction to Engineering",
            "units": 2.0,
            "difficulty": 2,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 011": {
            "name": "Statics",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B", "PHYS 008A")],  # AND relationship
            "unlocks": ["ENGR 012", "ENGR 013"],
            "department": "engineering",
        },
        "ENGR 012": {
            "name": "Dynamics",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("ENGR 011",)],
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 013": {
            "name": "Strength of Materials",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("ENGR 011",)],
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 014": {
            "name": "Materials of Engineering",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("CHEM 001A", "PHYS 008A")],  # AND relationship
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 015B": {
            "name": "Applied Mechanics",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 005B",)],
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 016": {
            "name": "Engineering Circuits",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("PHYS 008B", "MATH 055")],  # AND relationship
            "unlocks": ["ENGR 016L"],
            "department": "engineering",
        },
        "ENGR 016L": {
            "name": "Engineering Circuits Laboratory",
            "units": 1.0,
            "difficulty": 1,
            "assessment_allow": False,
            "prerequisites": [("ENGR 016",)],
            "unlocks": [],
            "department": "engineering",
        },
        "ENGR 018": {
            "name": "Programming and Problem-Solving in MATLAB",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("MATH 005A",)],
            "unlocks": [],
            "department": "engineering",
        },

        # Statistics Department
        "STAT 050": {
            "name": "Elementary Statistics",
            "units": 4.0,
            "difficulty": 4,
            "assessment_allow": True,  # Based on "placement into any Math course"
            "prerequisites": [],
            "unlocks": [],
            "department": "statistics",
        },

        # Computer Information Systems Department
        "CIS 010": {
            "name": "Introduction to Information Systems",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [],
            "unlocks": ["CIS 012", "CIS 062"],
            "department": "computer information systems",
        },
        "CIS 012": {
            "name": "Introduction to Programming Using Python",
            "units": 3.0,
            "difficulty": 3,
            "assessment_allow": False,
            "prerequisites": [("CIS 010",), ("MATH 003",)],  # OR relationship
            "unlocks": ["CIS 014", "CIS 016", "CIS 063", "CS 034"],
            "department": "computer information systems",
        }
    }
}

