"""update tables

Revision ID: 4edeba384943
Revises: 01838f0ad416
Create Date: 2025-05-20 00:22:44.358528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edeba384943'
down_revision: Union[str, None] = '01838f0ad416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articulation_group', 'universities', ['university_id'], ['id'])
    op.create_foreign_key(None, 'articulation_group', 'majors', ['major_id'], ['id'])
    op.create_foreign_key(None, 'articulation_group', 'colleges', ['college_id'], ['id'])
    op.create_foreign_key(None, 'expression_nodes', 'university_courses', ['university_course_id'], ['id'])
    op.create_foreign_key(None, 'expression_nodes', 'expression_nodes', ['parent_node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expression_nodes', type_='foreignkey')
    op.drop_constraint(None, 'expression_nodes', type_='foreignkey')
    op.drop_constraint(None, 'articulation_group', type_='foreignkey')
    op.drop_constraint(None, 'articulation_group', type_='foreignkey')
    op.drop_constraint(None, 'articulation_group', type_='foreignkey')
    # ### end Alembic commands ###
