"""Add articulated_group and articulated_group_courses

Revision ID: 74c0ef1184a1
Revises: b96237605cc0
Create Date: 2025-05-15 11:00:11.604845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c0ef1184a1'
down_revision: Union[str, None] = 'b96237605cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
