"""create models

Revision ID: 889aaba3e8dc
Revises: 35216c2dc901
Create Date: 2025-06-20 22:35:32.287210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889aaba3e8dc'
down_revision: Union[str, None] = '35216c2dc901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_articulation_group_root_node', 'articulation_group', 'expression_nodes', ['root_expression_node_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_articulation_group_root_node', 'articulation_group', type_='foreignkey')
    # ### end Alembic commands ###
