"""fresh start

Revision ID: b0dd9d64596e
Revises: 8ef64985a719
Create Date: 2025-04-17 21:15:05.120318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dd9d64596e'
down_revision: Union[str, None] = '8ef64985a719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_major_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_course_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['university_course_id'], ['university_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_course_id', 'major_id', name='unq_course_major')
    )
    op.create_index(op.f('ix_course_major_mappings_id'), 'course_major_mappings', ['id'], unique=False)
    op.add_column('university_courses', sa.Column('university_id', sa.Integer(), nullable=False))
    op.drop_constraint('university_courses_major_id_fkey', 'university_courses', type_='foreignkey')
    op.create_foreign_key(None, 'university_courses', 'universities', ['university_id'], ['id'])
    op.drop_column('university_courses', 'major_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university_courses', sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'university_courses', type_='foreignkey')
    op.create_foreign_key('university_courses_major_id_fkey', 'university_courses', 'majors', ['major_id'], ['id'])
    op.drop_column('university_courses', 'university_id')
    op.drop_index(op.f('ix_course_major_mappings_id'), table_name='course_major_mappings')
    op.drop_table('course_major_mappings')
    # ### end Alembic commands ###
