"""Add articulated_group and articulated_group_courses

Revision ID: b96237605cc0
Revises: e5c24ecfa765
Create Date: 2025-05-15 10:50:17.413241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96237605cc0'
down_revision: Union[str, None] = 'e5c24ecfa765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulation_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_course_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('operator', sa.Enum('AND', 'OR', name='relationshiptype'), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articulation_group_id'), 'articulation_group', ['id'], unique=False)
    op.create_table('articulation_group_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulation_group_id', sa.Integer(), nullable=False),
    sa.Column('community_college_course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulation_group_id'], ['articulation_group.id'], ),
    sa.ForeignKeyConstraint(['community_college_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articulation_group_courses_id'), 'articulation_group_courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articulation_group_courses_id'), table_name='articulation_group_courses')
    op.drop_table('articulation_group_courses')
    op.drop_index(op.f('ix_articulation_group_id'), table_name='articulation_group')
    op.drop_table('articulation_group')
    # ### end Alembic commands ###
