"""Add group_id and relationship_type to articulation_agreements

Revision ID: e43dd4ddb28d
Revises: 8b596fbbbe28
Create Date: 2025-05-17 16:19:54.400655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43dd4ddb28d'
down_revision: Union[str, None] = '8b596fbbbe28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulation_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_college_course_id', sa.Integer(), nullable=False),
    sa.Column('university_course_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.Enum('AND', 'OR', name='relationshiptype'), nullable=False),
    sa.ForeignKeyConstraint(['community_college_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['university_course_id'], ['university_courses.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articulation_agreements_id'), 'articulation_agreements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articulation_agreements_id'), table_name='articulation_agreements')
    op.drop_table('articulation_agreements')
    # ### end Alembic commands ###
