"""After merging with Jack 5/20

Revision ID: f9322ae8dcb1
Revises: 4edeba384943
Create Date: 2025-05-20 16:00:06.440899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9322ae8dcb1'
down_revision: Union[str, None] = '4edeba384943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('OPERATOR', 'COURSE', name='nodetype'), nullable=False),
    sa.Column('operator_type', sa.Enum('AND', 'OR', name='operatortype'), nullable=True),
    sa.Column('university_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['articulation_group.id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['expression_nodes.id'], ),
    sa.ForeignKeyConstraint(['university_course_id'], ['university_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expression_nodes_id'), 'expression_nodes', ['id'], unique=False)
    op.add_column('articulation_group', sa.Column('name', sa.String(), nullable=True))
    op.add_column('articulation_group', sa.Column('root_expression_node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articulation_group', 'expression_nodes', ['root_expression_node_id'], ['id'])
    op.drop_column('articulation_group', 'expression')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulation_group', sa.Column('expression', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articulation_group', type_='foreignkey')
    op.drop_column('articulation_group', 'root_expression_node_id')
    op.drop_column('articulation_group', 'name')
    op.drop_index(op.f('ix_expression_nodes_id'), table_name='expression_nodes')
    op.drop_table('expression_nodes')
    # ### end Alembic commands ###
